version: 0.0
os: linux
files:
  - source: target/__ARTIFACT__-all.tar.gz
    destination: /tmp
hooks:
  BeforeInstall:
    - location: scripts/before_install
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install
      timeout: 300
      runas: root      
  ApplicationStop:
    - location: scripts/app_stop
      timeout: 300
      runas: root
  ApplicationStart: 
    - location: scripts/app_start
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/app_tests
      timeout: 300
      runas: root